title: Elvin Shrestha Blog
author: GitHub User
email: elwyncrestha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my GitHub blog which will provide 
  brief information about my GitHub repositories.

# social links
twitter_username: elwyncrestha
github_username:  elwyncrestha

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
